#!/bin/bash

echo none > /sys/class/leds/rockpis:blue:user/trigger
while :
do
   if  mpc | grep playing >/dev/nul
   then
        echo none > /sys/class/leds/rockpis:green:power/trigger
   else
        echo default-on > /sys/class/leds/rockpis:green:power/trigger
   fi
done
