#!/bin/bash

i2cset -y 1 17 0 0x0f
i2cset -y 1 17 8 0x04
echo none > /sys/class/leds/rockpis:blue:user/trigger

while :
do
   if  mpc | grep playing >/dev/nul
   then
        echo none > /sys/class/leds/rockpis:green:power/trigger
   else
        echo default-on > /sys/class/leds/rockpis:green:power/trigger
   fi
done
